### ISSUE TITLE
Durability gained

### ISSUE THREAD

**Issue by Reignofmagic** [blaxxun-boop/Blacksmithing#1]
Hello, 

The Durability gained from blacksmith levels appears to not increase max durability, only the initial durability. 

Installed Extended Item Data Framework mod from Randy (which is not listed as dependency nor does it seem to be required by Blacksmithing) fixes this. 

If EIDF is supposed to be required/needed it isn't listed as so on the modpage through the Thunderstore

**Comment by blaxxun-boop** [comment]
No, it's not needed anymore. You may have old items that still use the EIDF way to store the durability.
