### ISSUE TITLE
Missing Blacksmithing Skill

### ISSUE THREAD

**Issue by Volikaris** [blaxxun-boop/Blacksmithing#3]
While using 1.2.2 I have Blacksmithing skill missing, the perks aren't working.
While using 1.2.0 Skill is back visible and working. 

Here's my profile code for debug?
0185bb5e-278f-a92f-6508-5ea358f32e57

**Comment by blaxxun-boop** [comment]
Sounds like you are using Valheim Plus. Blacksmithing doesn't work with Valheim Plus.
Check https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.

**Comment by Volikaris** [comment]
Thank you for your quick answer. I have read the topic, I'm on your side bro.
