### ISSUE TITLE
No loger generating config file

### ISSUE THREAD

**Issue by SuperMegaBuffet** [blaxxun-boop/Blacksmithing#5]
Noticed that the increased durability was no longer recognized in-game, as if the mod had been uninstalled. Deleted config files and reinstalled/launched game. No new config files were generated, game continues to run but does not change to add the blacksmithing skill.

**Comment by SuperMegaBuffet** [comment]
Edit: Looks like it is the problem with valheim plus compatibility.

**Comment by blaxxun-boop** [comment]
Yup, read this, if you wanna know why: https://github.com/blaxxun-boop/PassivePowers/issues/5
