### ISSUE TITLE
Incompatibility with Valheim Plus

### ISSUE THREAD

**Issue by Squallll94** [blaxxun-boop/Blacksmithing#7]
Hello Smoothbrain,

unfortunately many of your mods are incompatible with Valheim Plus.

Did you add this incompatibility to prevent issues?

For Blacksmith for example Valheim Plus also has the config to change weapon durability, but on default it is turned off.
Same goes for Foraging/ Farming - yield of crops.

Thank you
Squall

**Comment by witherfox** [comment]
I've been going through and creating issue requests with all the mods I'm finding from Smoothbrain that are not compatible with Valheim Plus and other mods. Hopefully it gets fixed soon!

**Comment by blaxxun-boop** [comment]
Yes, that is on purpose. If you get a message like this, the mod has been made incompatible by the mod author. Valheim Plus is a huge bully in the modding community and it needs to go.

Read https://github.com/blaxxun-boop/PassivePowers/issues/5 for more info.
