### ISSUE TITLE
Mod not working at all.

### ISSUE THREAD

**Issue by LepreSeanSD** [blaxxun-boop/Blacksmithing#8]
Added the mod via thunderstore but it's not working. It's enabled on my server and client but it's done nothing, no config file or anything.

**Comment by Deputydang** [comment]
I am having the same issue as @LepreSeanSD.  The only difference for me is that I am playing single player locally and not on a serve.  I have the latest version (1.2.2).

**Comment by blaxxun-boop** [comment]
Sounds like you are using Valheim Plus. None of my mods work with Valheim Plus.

For more info see https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by LepreSeanSD** [comment]
Ah, thank you.
